# Generated by Django 2.1.9 on 2019-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
